# Generated by Django 5.2.12 on 2026-05-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('church', models.CharField(blank=True, max_length=100, verbose_name="Église d'origine")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biographie')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Leader du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
