# Generated by Django 5.2.12 on 2026-05-08 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('coordination', '🎯 Coordination'), ('evangelisation', '📢 Évangélisation'), ('louange', '🎵 Louange'), ('enseignement', '📖 Enseignement'), ('technique', '💻 Technique / Médias'), ('communication', '📱 Communication'), ('accueil', '🤝 Accueil'), ('priere', '🙏 Prière'), ('social', '❤️ Action sociale')], max_length=20, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_regular_member',
            field=models.BooleanField(default=False, verbose_name='Prie déjà dans notre église'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_type',
            field=models.CharField(choices=[('staff', '👑 Membre du Staff'), ('regular', "🙏 Jeune de l'église"), ('guest', '👤 Invité')], default='guest', max_length=20, verbose_name='Type de membre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
